language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - npm install
  - npm run build
  - echo "Buildstep done"

script:
  - docker --version # print the version for logging
  - docker build -t udacity-3-frontend .
  - docker tag udacity-3-frontend fjenkel/udacity-3-frontend:latest

after_success:
  - echo "$DOCKER_ACCESS_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fjenkel/udacity-3-frontend
